"""Writes phase2/reports/phase2_5_report.md from the Phase 2.5 artifacts (spec section 24).

    python phase2/src/phase2_5_report.py

Every number comes from phase2/artifacts/phase2_5/*.json and the run summaries; the few
sentences of interpretation live in CONCLUSIONS below and are checked against those numbers.
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ART = REPO / "phase2" / "artifacts" / "phase2_5"
RUNS = REPO / "phase2" / "output" / "phase2_5" / "runs"
SOURCES = ("s2", "s3")


def load(name):
    return json.loads((ART / name).read_text(encoding="utf-8"))


def table(headers, rows):
    out = ["| " + " | ".join(map(str, headers)) + " |", "|" + "---|" * len(headers)]
    return "\n".join(out + ["| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ") for c in r) + " |"
                            for r in rows])


def pct(x, d=2):
    return "n/a" if x is None else f"{100 * x:.{d}f}%"


def f4(x):
    return "n/a" if x is None else f"{x:.4f}"


def ci(c):
    return f"[{c[0]:.4f}, {c[1]:.4f}]"


def run_summary(name):
    p = RUNS / f"{name}.summary.json"
    return json.loads(p.read_text(encoding="utf-8-sig")) if p.exists() else None


def main() -> None:
    base = load("baseline_reproduction.json")
    miss, abl, cut, cap, tr = (load(n) for n in ("blocking_miss_analysis.json", "blocking_ablation.json",
                                                 "key_cutoff_sensitivity.json", "cap_sensitivity.json",
                                                 "transliteration_blocking.json"))
    fa, mc, th = load("feature_ablation.json"), load("model_comparison.json"), load("threshold_robustness.json")
    res = load("full_scale_resource_test.json")
    final = load("final_comparison.json")
    concl = json.loads((ART / "conclusions.json").read_text(encoding="utf-8"))
    scales = [s for s in ("dev", "10k") if s in miss]
    L = ["# Phase 2.5 Report: Hardening the Phase 2 Baseline", "",
         "Generated by `phase2/src/phase2_5_report.py` from `phase2/artifacts/phase2_5/`. Scales: **dev** = 5,000 "
         "Source-1 entities against 100,000 target records per source (the Phase 2 development setting); "
         "**10k** = 10,000 Source-1 entities against the complete Source-2 (5.03M) and Source-3 (5.29M) files; "
         "**50k** = 50,000 Source-1 entities against the complete target files. Every comparison within a scale "
         "uses identical validation Source-1 entities (20%, seed 42). Confidence intervals are 95% percentile "
         "bootstrap intervals over validation entities (B = 1,000, numpy seed 42, paired across configurations).", ""]

    # ------------------------------------------------------------ 1
    L += ["## 1. Executive Summary", ""] + [p + "\n" for p in concl["executive_summary"]]

    # ------------------------------------------------------------ 2
    rep = base["b0_reproduction"]
    L += ["## 2. Baseline Reproduction (Step 0)", "",
          f"B0 reproduced: **{'yes' if base['reproduced'] else 'no'}**. The unchanged Phase 2 configuration was run "
          "three times into `phase2/output/phase2_5/`: before any change, after a behavior-preserving split of "
          "`build_blocking` into `rule_tables` + `apply_cutoff` (needed to test several cutoffs cheaply), and on the "
          "final Phase 2.5 code. All three produced artifacts, submission files and a model file byte-identical to the "
          "original B0 files, which were not modified.", "",
          table(["metric", "spec (B0 report)", "reproduced", "match"],
                [[k, v, rep["metrics"][k], "yes" if base["matches_spec_b0"][k] else "NO"]
                 for k, v in base["spec_reported_b0"].items()]
                + [["train/validation entity overlap", 0, rep["metrics"]["train_validation_entity_overlap"], "yes"]]), "",
          f"Validator on the reproduced dev outputs: {'PASS' if rep['validator']['with_candidates']['passed'] else 'FAIL'} "
          f"(`{rep['validator']['with_candidates']['command']}`). Wall time {rep['wall_seconds']} s; main-process peak "
          f"working set {rep['main_process_peak_working_set_mb']} MB ({rep['memory_method']}).", ""]

    # ------------------------------------------------------------ 3
    L += ["## 3. Blocking-Miss Analysis (Step 1)", "",
          "Every validation positive absent from the B0 candidate set was analyzed: raw and normalized names and "
          "addresses, script mismatch, transliteration/phonetic and name/address similarities, house/postal/state "
          "evidence, the outcome of every B0 rule with the exact reason it failed (no key on a side, keys differ, or "
          "shared key skipped because its bucket exceeded 100 target records), whether the pair was retrieved but "
          "removed by the per-S1 cap, and whether each proposed Phase 2.5 rule would retrieve it. Categories are "
          "multi-label; the primary category is the first applicable one in the order listed. "
          "\"No existing block overlap\" is a factual tag (no rule shares any key); \"Unknown\" is assigned when no "
          "evidence-based category applies. Full per-pair records: `blocking_miss_analysis.json`.", ""]
    cats = miss[scales[-1]]["category_order"]
    L += [table(["category"] + [f"{s}: primary" for s in scales] + [f"{s}: any" for s in scales],
                [[c] + [miss[s]["primary_category_counts"].get(c, 0) for s in scales]
                 + [miss[s]["any_category_counts"].get(c, 0) for s in scales] for c in cats]
                + [["**total validation positives missed**"] + [miss[s]["validation_positives_missed"] for s in scales]
                   + ["" for _ in scales]]), "",
          "Missed pairs a proposed rule would retrieve: "
          + "; ".join(f"{s}: " + ", ".join(f"{k} {v}" for k, v in miss[s]["recoverable_by_proposed_rule"].items())
                      for s in scales) + ".", ""]
    for s in scales:
        ex = [m for m in miss[s]["misses"]][:6]
        L += [f"Examples ({s}):", "",
              table(["S1 / target", "primary category", "S1 name / target name", "S1 address / target address"],
                    [[f"{m['s1']} / {m['target']}", m["primary_category"],
                      f"{m['raw']['s1_name']} / {m['raw']['target_name']}",
                      f"{m['raw']['s1_address']} / {m['raw']['target_address']}"] for m in ex]), ""]

    # ------------------------------------------------------------ 4
    L += ["## 4. Blocking Rule Ablation (Step 2)", "",
          "Measured on the B0 union before the per-S1 cap (cutoff 100). \"Unique-only\" = positives no other rule "
          "retrieves. Shapley recall = the rule's average marginal recall over all 8! orders (exact over the 256 "
          "rule subsets), so it does not depend on rule order; Shapley values sum to the union recall.", ""]
    for s in scales:
        for src in SOURCES:
            a = abl[s]["by_source"][src]
            L += [f"**{s}, {src.upper()}** (union pre-cap recall {pct(a['union_precap_recall'])}, "
                  f"{a['union_precap_pairs']:,} pairs)", "",
                  table(["rule", "pairs", "TPs", "recall", "unique-only TPs", "Shapley recall", "Shapley pairs",
                         "mean/p95 per S1", "largest kept bucket", "skipped keys", "TPs lost to skipped keys"],
                        [[r, f"{v['pairs']:,}", f"{v['true_positives']:,}", pct(v["recall"]), v["unique_only_positives"],
                          pct(v["shapley_recall"]), f"{v['shapley_pairs']:,.0f}",
                          f"{v['mean_per_s1']} / {v['p95_per_s1']}", v["largest_kept_bucket"], f"{v['skipped_keys']:,}",
                          v["true_positives_lost_to_skipped_keys"]] for r, v in a["rules"].items()]), "",
                  "Cumulative (listed order): " + ", ".join(f"+{c['rules_added_so_far'][-1]} → {pct(c['recall'])}"
                                                           for c in a["cumulative_in_listed_order"]), ""]

    # ------------------------------------------------------------ 5
    L += ["## 5. Candidate Cap Sensitivity (Step 3)", "",
          "Recall after the cap, candidates per S1 after the cap, positives lost to the cap and the time the cap "
          "step took, at the B0 cutoff of 100 (other cutoffs: `cap_sensitivity.json`).", ""]
    for s in scales:
        for src in SOURCES:
            c = cap[s]["by_source_by_cutoff"][src]["100"]
            L += [f"**{s}, {src.upper()}**", "",
                  table(["cap", "recall", "pairs before cap", "pairs after cap", "mean / p95 / max per S1",
                         "positives lost to cap", "recall lost to cap", "cap seconds"],
                        [[k, pct(v["recall"]), f"{v['pairs_before_cap']:,}", f"{v['after_cap']['pairs']:,}",
                          f"{v['after_cap']['mean_per_s1']} / {v['after_cap']['p95_per_s1']} / {v['after_cap']['max_per_s1']}",
                          v["positives_lost_to_cap"], pct(v["recall_lost_to_cap"]), v["cap_seconds"]]
                         for k, v in c.items()]), ""]

    # ------------------------------------------------------------ 6
    L += ["## 6. High-Frequency-Key Sensitivity (Step 4)", "",
          "Pre-cap recall and candidate volume for each oversized-key cutoff, and recall after the B0 cap of 60 "
          "(the cap interacts with the cutoff: more pairs per S1 means the cap removes more). \"No cutoff\" is a "
          "diagnostic only: its recall is the share of positives sharing any key, and its pair count is an upper "
          "bound computed from bucket sizes, never materialized.", ""]
    for s in scales:
        for src in SOURCES:
            cs = cut[s]["by_source"][src]
            rows = [[k, pct(v["precap_recall"]), f"{v['precap']['pairs']:,}", f"{v['precap']['mean_per_s1']} / "
                     f"{v['precap']['p95_per_s1']} / {v['precap']['max_per_s1']}",
                     max(b["largest_kept_bucket"] for b in v["buckets"].values()),
                     sum(b["skipped_keys"] for b in v["buckets"].values()), v["positives_lost_sharing_skipped_key"],
                     v["blocking_seconds"], pct(cap[s]["by_source_by_cutoff"][src][k]["60"]["recall"])]
                    for k, v in cs.items() if k != "no_cutoff_diagnostic"]
            nc = cs["no_cutoff_diagnostic"]
            rows.append(["none (diagnostic)", pct(nc["recall_upper_bound"]), f"≤ {nc['pair_count_upper_bound']:,}", "",
                         nc["largest_bucket"], 0, "", "not run", ""])
            L += [f"**{s}, {src.upper()}**", "",
                  table(["cutoff", "pre-cap recall", "pre-cap pairs", "mean / p95 / max per S1", "largest bucket",
                         "skipped keys", "positives lost sharing a skipped key", "blocking seconds", "recall after cap 60"],
                        rows), ""]

    # ------------------------------------------------------------ 7 / 8
    def exp_rows(s, src, names):
        rows = []
        for k in names:
            v = {**abl[s]["address_blocking"][src], **tr[s]["by_source"][src]}.get(k)
            if v is None:
                continue
            b = v["buckets"]
            rows.append([k, f"{v['rule_alone']['pairs']:,}", pct(v["rule_alone"]["recall"]),
                         max(x["largest_kept_bucket"] for x in b.values()), max(x["p99_kept_bucket"] for x in b.values()),
                         sum(x["skipped_keys"] for x in b.values()), f"{v['new_pairs_vs_b0_precap']:,}",
                         v["b0_missed_positives_retrieved"], pct(v["b0_after_cap_recall"]),
                         pct(v["with_b0_after_cap"]["recall"]), v["with_b0_after_cap"]["mean_per_s1"]])
        return rows
    hdr = ["rule(s)", "pairs alone", "recall alone", "largest kept bucket", "p99 bucket", "skipped keys",
           "new pairs vs B0", "B0-missed positives retrieved", "B0 recall (cap 60)", "B0 + rule recall (cap 60)",
           "B0 + rule mean per S1"]
    L += ["## 7. Transliteration Blocking (Step 5)", "",
          "Experimental rule `name_phonetic_token`: the two rarest per-token consonant skeletons of the romanized "
          "core name (Indic scripts are romanized deterministically by the existing Phase 2 normalization, which "
          "was not changed). Keys are exact-match buckets with the same 100-record cutoff; no all-pairs search.", ""]
    for s in scales:
        for src in SOURCES:
            L += [f"**{s}, {src.upper()}**", "", table(hdr, exp_rows(s, src, ["name_phonetic_token"])), ""]
    L += ["## 8. Address Blocking (Step 6)", "",
          "Experimental address-first rules: house number + rare locality token, postal code + rare locality token, "
          "state + rare locality token, and a sorted signature of the non-numeric, non-state address components.", ""]
    names = ["house_locality", "postal_locality", "state_locality", "address_signature",
             "house_locality+postal_locality+state_locality+address_signature",
             "name_phonetic_token+house_locality+postal_locality+state_locality+address_signature"]
    for s in scales:
        for src in SOURCES:
            L += [f"**{s}, {src.upper()}**", "", table(hdr, exp_rows(s, src, names)), ""]

    # ------------------------------------------------------------ 9
    L += ["## 9. Feature Ablation (Steps 7 and 8)", "",
          "Same frozen B0 candidate set, labels, fit rows (5 negatives per positive, half hard, seed 42) and "
          "validation entities for every set; logistic regression (M0); threshold chosen on validation.", ""]
    for s in scales:
        f = fa[s]
        boot = f["bootstrap"]["configurations"]
        L += [f"**{s}** ({f['protocol']['validation_entities']:,} validation entities)", "",
              table(["set", "features", "threshold", "macro F0.5", "95% CI", "difference vs B0 [95% CI]", "verdict",
                     "precision", "recall", "FP", "FN"],
                    [[k, v["n_features"], v["selected_threshold"], f4(v["macro_f05"]), ci(boot[k]["ci95"]),
                      f"{boot[k]['diff_vs_B0']:+.4f} {ci(boot[k]['diff_vs_B0_ci95'])}", boot[k]["verdict"],
                      f4(v["precision"]), f4(v["recall"]), v["fp"], v["fn"]] for k, v in f["results"].items()]), "",
              f"Selected feature set: {f['selected_feature_set']} ({f['selection_reason']}).", ""]
        d = f["name_edit_sim_diagnosis"]
        sc = d["conditional_model_contribution"]["standardized_coefficient"]
        corr = d["correlation"]
        L += [f"`name_edit_sim` ({s}): correlation with the label {corr['with_label']:.3f}; strongest correlations "
              "with other name features: " + ", ".join(f"{k} {v:.3f}" for k, v in sorted(
                  corr["with_name_similarity_features"].items(), key=lambda kv: -abs(kv[1] or 0))[:3])
              + f". Standardized coefficient in B0 {sc['B0']}, alone {sc['univariate']}, and with its |r| ≥ 0.9 "
              f"correlates removed {sc['B0_minus_abs_r_ge_0.9_correlates']}.", ""]
    L += [concl["name_edit_sim"], ""]

    # ------------------------------------------------------------ 10
    L += ["## 10. Model Comparison (Step 9)", "",
          "M0 = StandardScaler + LogisticRegression (B0). M1 = HistGradientBoostingClassifier(max_iter=200, "
          "random_state=42, early_stopping=False). Same candidates, features, fit rows, validation entities and "
          "threshold protocol; no hyperparameter search.", ""]
    for s in scales:
        m = mc[s]
        boot = m["bootstrap"]["configurations"]
        L += [f"**{s}**", "",
              table(["model / features", "threshold", "macro F0.5", "95% CI", "difference vs M0/B0 [95% CI]",
                     "verdict", "precision", "recall", "FP", "FN", "blocking-missed", "classifier-missed",
                     "fit s", "score s"],
                    [[k, v["selected_threshold"], f4(v["macro_f05"]), ci(boot[k]["ci95"]),
                      f"{boot[k][[x for x in boot[k] if x.startswith('diff_vs') and not x.endswith('ci95')][0]]:+.4f} "
                      f"{ci(boot[k][[x for x in boot[k] if x.endswith('ci95') and x.startswith('diff')][0]])}",
                      boot[k]["verdict"], f4(v["precision"]), f4(v["recall"]), v["fp"], v["fn"],
                      v["blocking_missed_positives"], v["classifier_missed_positives"], v["fit_seconds"],
                      v["scoring_seconds"]] for k, v in m["results"].items()]), ""]

    # ------------------------------------------------------------ 11 / 12
    L += ["## 11. Threshold Robustness (Step 10)", ""]
    for s in scales:
        for name, c in th[s]["configurations"].items():
            rows = [[r["threshold"], f4(r["macro_f05"]), f4(r["precision"]), f4(r["recall"]), r["tp"], r["fp"], r["fn"],
                     r["predictions"], r["zero_match_predicted_empty"], r["zero_match_false_merges"],
                     r["singleton_exact_correct"], r["singleton_missed"]]
                    for r in c["thresholds"] if 0.5 <= r["threshold"] <= 0.9]
            L += [f"**{s}, {name}**: selected {c['selected_threshold_standard_protocol']} on the standard 0.05 grid; "
                  f"best on the combined grid {c['best_on_combined_grid']}; macro F0.5 within ±0.1 of the selected "
                  f"threshold ranges over {ci(c['macro_f05_range_within_0.1_of_selected'])}.", "",
                  table(["threshold", "macro F0.5", "precision", "recall", "TP", "FP", "FN", "predictions",
                         "zero-match empty", "zero-match false merges", "singletons exact", "singletons missed"], rows), ""]
    L += ["## 12. Singleton and Zero-Match Analysis (Step 11)", "",
          "No rule forces a prediction: an entity gets matches only for candidates scoring at or above the "
          "threshold, and an empty `matched_entity_ids` is written otherwise.", ""]
    stress = []
    for s in scales:
        for name, c in th[s]["configurations"].items():
            st = c["stress_test"]
            stress.append([f"{s}, {name}", st["threshold"], st["true_zero_match"], st["zero_match_correctly_empty"],
                           st["zero_match_false_merges"], st["true_singleton"], pct(st["singleton_correct_match_rate"], 1),
                           st["singleton_misses"], st["true_multi_match"],
                           f"{st['multi_match']['mean_true']:.2f} / {st['multi_match']['mean_predicted']:.2f}",
                           st["average_predictions_per_s1"]])
    labels = {"resource_b0_50000": "50k, B0", "blocking_lr_50000": "50k, frozen blocking + LR", "frozen_50000": "50k, frozen"}
    for name, st in final.get("stress_tests", {}).items():
        stress.append([labels[name], st["threshold"], st["true_zero_match"], st["zero_match_correctly_empty"],
                       st["zero_match_false_merges"], st["true_singleton"], pct(st["singleton_correct_match_rate"], 1),
                       st["singleton_misses"], st["true_multi_match"],
                       f"{st['multi_match']['mean_true']:.2f} / {st['multi_match']['mean_predicted']:.2f}",
                       st["average_predictions_per_s1"]])
    L += [table(["scale, model", "threshold", "zero-match entities", "correctly empty", "false merges", "singletons",
                 "singleton exact-correct", "singleton misses", "multi-match entities", "multi: mean true / predicted",
                 "avg predictions per S1"], stress), ""]

    # ------------------------------------------------------------ 13
    L += ["## 13. Full-Scale Resource Test (Step 12)", "",
          table(["run", "S1 entities", "targets", "wall s", "main peak MB", "all python peak MB", "workers",
                 "S1 chunk", "candidate pairs S2 / S3", "candidate recall S2 / S3"],
                [[k, f"{v['source1_entities']:,}", v["targets"], v["wall_seconds"], v["main_process_peak_working_set_mb"],
                  v["all_python_processes_peak_mb"], v.get("workers", ""), v.get("source1_chunk_size", ""),
                  " / ".join(f"{v['candidate_pairs'][x]:,}" for x in SOURCES) if "candidate_pairs" in v else "",
                  " / ".join(pct(v["candidate_recall"][x]) for x in SOURCES) if "candidate_recall" in v else ""]
                 for k, v in res["runs"].items()]), "",
          f"Cartesian product: {res['cartesian_product']}. Memory: {res['memory_method']}.", ""]
    if "projection_full_run" in res:
        pj = res["projection_full_run"]
        L += [f"Projection of test inference over all 1,732,544 test Source-1 entities with the frozen configuration "
              f"({pj['method']}):", "",
              table(["source", "load + normalize s", "index build s", "join + cap s", "candidate pairs", "features s",
                     "feature pairs/s", "total s"],
                    [[s.upper(), v["load_normalize_s"], v["index_build_s"], v["join_and_cap_s"],
                      f"{v['test_candidate_pairs']:,}", v["features_s"], f"{v['feature_pairs_per_second']:,}", v["total_s"]]
                     for s, v in pj["test_inference_by_source"].items()]), "",
              f"Total about {pj['test_inference_total_seconds_estimate'] / 3600:.1f} h for "
              f"{pj['test_candidate_pairs_estimate']:,} candidate pairs. {pj['peak_memory_note']}", ""]
    L += [concl["resources"], ""]

    # ------------------------------------------------------------ 14-17
    L += ["## 14. Final Hardened Configuration", "", concl["final_configuration"], "",
          "## 15. Before vs After Metrics", "",
          f"50k Source-1 entities against the full target files; identical validation entities "
          f"({list(final['runs'].values())[0]['validation_entities']:,}) for every row; paired bootstrap against B0.", ""]
    boot = final["bootstrap"]["configurations"]
    ref = final["reference"]
    L += [table(["configuration", "candidate recall (S2 / S3 / combined)", "candidates per S1 (S2 + S3)",
                 "threshold", "macro F0.5", "95% CI", "difference vs B0 [95% CI]", "precision", "recall", "FP", "FN",
                 "blocking-missed", "classifier-missed"],
                [[concl["run_labels"].get(k, k),
                  f"{pct(v['candidate_recall_s2'])} / {pct(v['candidate_recall_s3'])} / {pct(v['candidate_recall'])}",
                  v["mean_candidates_per_s1"], v["selected_threshold"], f4(v["macro_f05"]), ci(boot[k]["ci95"]),
                  f"{boot[k][f'diff_vs_{ref}']:+.4f} {ci(boot[k][f'diff_vs_{ref}_ci95'])}", f4(v["precision"]),
                  f4(v["recall"]), v["fp"], v["fn"], v["blocking_missed_positives"], v["classifier_missed_positives"]]
                 for k, v in final["runs"].items()]), "",
          "### Post-improvement error analysis (Step 14)", "",
          f"On the same 10,000 validation entities, the frozen candidate set contains "
          f"{final['previously_blocking_missed_now_retrieved']['count']:,} positives that B0's blocking never retrieved; "
          f"{final['previously_blocking_missed_now_retrieved']['now_predicted_at_threshold']:,} of them are now predicted. "
          f"Remaining: {final['post_improvement']['frozen_50000']['false_negatives_never_retrieved']:,} blocking misses, "
          f"{final['post_improvement']['frozen_50000']['false_negatives_scored_below_threshold']:,} retrieved positives "
          f"scored below the threshold, {final['post_improvement']['frozen_50000']['false_positives']:,} false positives "
          f"(zero-match false merges {final['stress_tests']['frozen_50000']['zero_match_false_merges']} of "
          f"{final['stress_tests']['frozen_50000']['true_zero_match']}; singleton misses "
          f"{final['stress_tests']['frozen_50000']['singleton_misses']} of {final['stress_tests']['frozen_50000']['true_singleton']}). "
          "The miss categories of section 3 (10k) remain the best description of the remaining blocking misses: "
          "oversized keys first, then transliteration and truncated addresses. Examples below come from "
          "`phase2/output/phase2_5/frozen_50000/artifacts/error_analysis.json`.", ""]
    ea = json.loads((REPO / "phase2" / "output" / "phase2_5" / "frozen_50000" / "artifacts" / "error_analysis.json")
                    .read_text(encoding="utf-8"))
    for key, title in (("false_positives", "Highest-scoring false positives (often near-duplicate businesses)"),
                       ("false_negatives_scored_below_threshold", "Lowest-scoring retrieved false negatives"),
                       ("false_negatives_never_retrieved", "Remaining blocking misses")):
        L += [f"**{title}**", "", table(["S1 / target", "score", "S1 name / target name", "S1 address / target address"],
                                        [[f"{e['s1']} / {e['target']}", e["score"], f"{e['s1_name']} / {e['target_name']}",
                                          f"{e['s1_address']} / {e['target_address']}"] for e in ea[key]["examples"][:6]]), ""]
    L += ["### Required final comparison (spec section 25)", "",
          table(["Configuration", "Candidate Recall", "Candidates/S1", "Macro F0.5", "Precision", "Recall", "Notes"],
                concl["section25_rows"]), "",
          "## 16. Remaining Limitations", ""] + [f"- {x}" for x in concl["limitations"]] + [
          "", "## 17. Phase 3 Handoff", ""] + [f"- {x}" for x in concl["handoff"]] + [
          "", "## Dependencies", "", concl["dependencies"], ""]
    path = REPO / "phase2" / "reports" / "phase2_5_report.md"
    path.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
